In [28]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [29]:
df=pd.read_csv(r'C:\Users\Albii\Downloads\Student_Performance.csv')
df

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                        Yes          9.0   
1               4.0             82.0                         No          4.0   
2               8.0             51.0                        Yes          7.0   
3               5.0             52.0                        Yes          5.0   
4               7.0             75.0                         No          8.0   
...             ...              ...                        ...          ...   
9995            1.0             49.0                        Yes          4.0   
9996            7.0             64.0                        Yes          8.0   
9997            6.0             83.0                        Yes          8.0   
9998            9.0             97.0                        Yes          7.0   
9999            7.0             74.0                         No          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[10000 rows x 6 columns]

In [30]:
df.isnull().sum()

Hours Studied                       2
Previous Scores                     5
Extracurricular Activities          9
Sleep Hours                         8
Sample Question Papers Practiced    6
Performance Index                   0
dtype: int64

In [31]:
df=df.dropna()

In [32]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9982 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Hours Studied                     9982 non-null   float64
 1   Previous Scores                   9982 non-null   float64
 2   Extracurricular Activities        9982 non-null   object 
 3   Sleep Hours                       9982 non-null   float64
 4   Sample Question Papers Practiced  9982 non-null   float64
 5   Performance Index                 9982 non-null   int64  
dtypes: float64(4), int64(1), object(1)
memory usage: 545.9+ KB


In [34]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Extracurricular Activities"]=le.fit_transform(df["Extracurricular Activities"])
df

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0               7.0             99.0                           1          9.0   
1               4.0             82.0                           0          4.0   
2               8.0             51.0                           1          7.0   
3               5.0             52.0                           1          5.0   
4               7.0             75.0                           0          8.0   
...             ...              ...                         ...          ...   
9995            1.0             49.0                           1          4.0   
9996            7.0             64.0                           1          8.0   
9997            6.0             83.0                           1          8.0   
9998            9.0             97.0                           1          7.0   
9999            7.0             74.0                           0          8.0   

      Sample Question Papers Practiced  Performance Index  
0                                  1.0                 91  
1                                  2.0                 65  
2                                  2.0                 45  
3                                  2.0                 36  
4                                  5.0                 66  
...                                ...                ...  
9995                               2.0                 23  
9996                               5.0                 58  
9997                               5.0                 74  
9998                               0.0                 95  
9999                               1.0                 64  

[9982 rows x 6 columns]

In [35]:
x=df.iloc[:,:5].values
y=df.iloc[:,-1].values

In [36]:
x

array([[ 7., 99.,  1.,  9.,  1.],
       [ 4., 82.,  0.,  4.,  2.],
       [ 8., 51.,  1.,  7.,  2.],
       ...,
       [ 6., 83.,  1.,  8.,  5.],
       [ 9., 97.,  1.,  7.,  0.],
       [ 7., 74.,  0.,  8.,  1.]])

In [37]:
y

array([91, 65, 45, ..., 74, 95, 64], dtype=int64)

In [38]:
y=y.reshape(-1,1)

In [39]:
y

array([[91],
       [65],
       [45],
       ...,
       [74],
       [95],
       [64]], dtype=int64)

In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=100)

In [41]:
x_train

array([[ 5., 61.,  1.,  7.,  4.],
       [ 9., 65.,  1.,  4.,  8.],
       [ 5., 70.,  0.,  5.,  3.],
       ...,
       [ 7., 47.,  0.,  6.,  7.],
       [ 9., 81.,  1.,  7.,  9.],
       [ 1., 52.,  0.,  8.,  7.]])

In [42]:
y_train

array([[49],
       [62],
       [52],
       ...,
       [37],
       [82],
       [25]], dtype=int64)

In [43]:
from sklearn.linear_model import LinearRegression
lreg=LinearRegression()
lreg.fit(x_train,y_train)

LinearRegression()

In [44]:
ypred=lreg.predict(x_test)

In [45]:
ypred

array([[41.41218078],
       [38.91473741],
       [44.0131503 ],
       ...,
       [32.31381117],
       [62.89195133],
       [73.02309617]])

In [46]:
from sklearn.metrics import r2_score
r2_score(y_test,ypred)

0.9893120917802117